version: '3'

services:
  inventory:
    build: ./inventory-service
    ports:
      - 5002:5002
  shipping:
    build: ./shipping-service
    ports:
      - 5000:5000
  users:
    build: ./users-service
    ports:
      - 5005:5005
  billing:
    build: ./billing-service
    ports:
      - 5004:5004